#!/bin/env python3

from flask import Flask, jsonify, request
from flask_restful import Api, reqparse
from OpenSSL import crypto
from pymongo import MongoClient
import json
import os
import secrets
import random

# Configure flask container
app = Flask(__name__)
app.config['JSONIFY_PRETTYPRINT_REGULAR'] = True
api = Api(app)

# OpenSSL Validity for certificates
serial = 0
validity = 10*365*24*60*60


def bootstrap_key():
    ca_key = crypto.PKey()
    ca_key.generate_key(crypto.TYPE_RSA, 4096)
    return ca_key


def bootstrap_cert(ca_key):
    ca_cert = crypto.X509()
    ca_cert.set_version(2)
    ca_cert.set_serial_number(random.randint(50000000, 100000000))
    ca_subj = ca_cert.get_subject()
    ca_subj.commonName = os.environ['HOSTNAME']
    ca_cert.add_extensions([
        crypto.X509Extension(b"subjectKeyIdentifier", False, b"hash", subject=ca_cert),
    ])
    ca_cert.add_extensions([
        crypto.X509Extension(b"authorityKeyIdentifier", False, b"keyid:always", issuer=ca_cert),
    ])
    ca_cert.add_extensions([
        crypto.X509Extension(b"basicConstraints", False, b"CA:TRUE"),
        crypto.X509Extension(b"keyUsage", False, b"keyCertSign, cRLSign"),
    ])
    ca_cert.gmtime_adj_notBefore(serial)
    ca_cert.gmtime_adj_notAfter(validity)
    ca_cert.set_issuer(ca_subj)
    ca_cert.set_pubkey(ca_key)
    ca_cert.sign(ca_key, 'sha512')
    return ca_cert


def bootstrap():
    client = MongoClient(os.environ['mongodb'])
    db = client.CA
    do_bootstrap = db.sign.find_one({'Hostname': os.environ['HOSTNAME']})
    if not do_bootstrap:
        key_data = bootstrap_key()
        cert_data = bootstrap_cert(key_data)
        signing_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, key_data).decode("utf-8")
        signing_cert = crypto.dump_certificate(crypto.FILETYPE_PEM, cert_data).decode("utf-8")
        head = {
            'Hostname': os.environ['HOSTNAME'],
            'SSL': {
                'CERT': signing_cert.splitlines(),
                'KEY': signing_key.splitlines(),
            }
        }
        data = db.sign.insert_one(head)
        if data:
            client.close()
            return 'Success'
    else:
        client.close()
        return 'CA Certificates already exist'


def json_convert(data):
    response = json.dumps(data, default=str)
    return response


def argparse():
    parser = reqparse.RequestParser()
    parser.add_argument('Hostname',
                        type=str,
                        required=True,
                        help='hostname for certificate creation')
    parser.add_argument('SAN',
                        type=str,
                        help='san for use in certificate creation')
    parser.add_argument('API_KEY',
                        type=str,
                        required=True,
                        help='api key to validate endpoint connection')
    args = parser.parse_args()
    return args


def get_key():
    client = MongoClient(os.environ['mongodb'])
    db = client.CA
    data = db.certs.find({}, {"_id": 0, "api_key": 1})
    client.close()
    for content in data:
        if "api_key" in content:
            return content


def gen_key():
    key = crypto.PKey()
    key.generate_key(crypto.TYPE_RSA, 4096)
    return key


def gen_cert(args, key):
    cert = crypto.X509()
    cert.get_subject().C = os.environ['country']
    cert.get_subject().ST = os.environ['state']
    cert.get_subject().L = os.environ['locality']
    cert.get_subject().O = os.environ['org']
    cert.get_subject().OU = os.environ['unit']
    cert.get_subject().CN = args.Hostname
    if args.SAN:
        cert.get_subject().SN = args.SAN + request.remote_addr
    cert.get_subject().emailAddress = os.environ['email']
    cert.set_serial_number(serial)
    cert.gmtime_adj_notBefore(0)
    cert.gmtime_adj_notAfter(validity)
    cert.set_issuer(cert.get_subject())
    cert.set_pubkey(key)
    cert.sign(key, 'sha512')
    return cert


@app.route('/key', methods=['GET', 'POST', 'DELETE'])
def key():
    client = MongoClient(os.environ['mongodb'])
    db = client.CA
    if request.method == 'GET':
        data = get_key()
        return jsonify(data)

    elif request.method == 'POST':
        curr_key = get_key()
        new_key = secrets.token_urlsafe(32)

        if curr_key is None:
            db.certs.insert_one({'api_key': new_key})
            client.close()
            return jsonify(new_key)

        else:
            client.close()
            return 'Please delete the current key before creating a new one.\n'

    elif request.method == 'DELETE':
        api_key = get_key()
        db.certs.delete_one(api_key)
        return jsonify(api_key)


@app.route('/certs', methods=['GET', 'POST', 'DELETE'])
def certs():
    args = argparse()
    client = MongoClient(os.environ['mongodb'])
    db = client.CA

    if request.method == 'GET':
        data = db.certs.find_one({'Hostname': args.Hostname})
        client.close()
        return json.dumps(data, default=str)

    elif request.method == 'POST':
        args = argparse()
        key = gen_key()
        cert = gen_cert(args, key)
        json_cert = crypto.dump_certificate(crypto.FILETYPE_PEM, cert).decode("utf-8")
        json_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, key).decode("utf-8")
        head = {
            'Hostname': args.Hostname,
            'Requester IP': request.remote_addr,
            'SSL': {
                'CERT': json_cert.splitlines(),
                'KEY': json_key.splitlines(),
            }
        }
        data = db.certs.insert_one(head)
        client.close()
        if data:
            return 'success'

    elif request.method == 'DELETE':
        data = db.certs.delete_one({'Hostname': args.Hostname})
        client.close()
        if data:
            return 'success'
        else:
            return 'failed'


if __name__ == "__main__":
    bootstrap()
    app.run(debug=True, host='0.0.0.0')
